# Generated by Django 4.1.8 on 2023-07-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfid_db_table',
            name='count_value',
            field=models.IntegerField(blank=True, default=0, max_length=100),
            preserve_default=False,
        ),
    ]
