# Generated by Django 4.1.8 on 2023-07-12 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_rfid_db_table_count_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rfid_db_table',
            name='count_value',
        ),
    ]
